organize result previews into one menu
Psych-Slice/P-Slice pull request #72
Opened 2024-11-11 23:26 UTC by liamp0924

2024-11-12 06:50 UTC, mikolka9144 reviewed
Looks good. I'll have to do more tests before merging

2024-11-12 06:50 UTC, mikolka9144 commented on source/states/editors/ResultPreviewMenu.hx
> +		DiscordClient.changePresence("Editors Main Menu", null);
It would be better if it was unique

2024-11-12 06:50 UTC, mikolka9144 commented on source/states/editors/ResultPreviewMenu.hx
> +			directoryTxt.text = '< No Mod Directory Loaded >';
Not 100% if mod selector is needed to test result screens.

2024-11-12 20:23 UTC, liamp0924 commented on source/states/editors/ResultPreviewMenu.hx
> +			directoryTxt.text = '< No Mod Directory Loaded >';
i was just lazy and copy and pasted master editor menu and changed shit

2024-11-12 20:24 UTC, liamp0924 commented on source/states/editors/ResultPreviewMenu.hx
> +			directoryTxt.text = '< No Mod Directory Loaded >';
mb i didnt see that

2024-11-12 20:37 UTC, liamp0924 commented on source/states/editors/ResultPreviewMenu.hx
> +			directoryTxt.text = '< No Mod Directory Loaded >';
> Not 100% if mod selector is needed to test result screens.

https://www.mediafire.com/file/lfvb4n18tv022iz/ResultPreviewMenu.hx/file

improved the menu

2024-11-12 21:09 UTC, liamp0924 commented on source/states/editors/ResultPreviewMenu.hx
> +			directoryTxt.text = '< No Mod Directory Loaded >';
@mikolka9144 i have updated the pull request

2024-11-12 21:48 UTC, mikolka9144 requested changes

2024-11-12 21:48 UTC, mikolka9144 commented on assets/shared/sounds/breakfast.ogg
???

Why is this added as a sound?

2024-11-12 21:48 UTC, mikolka9144 commented on source/states/editors/ResultPreviewMenu.hx
> +		FlxG.sound.play(Paths.sound('breakfast'));
This should play music instead of sound (so that it loops properly)

2024-11-12 21:48 UTC, mikolka9144 commented on source/states/editors/ResultPreviewMenu.hx
> +			MusicBeatState.switchState(new MainMenuState());
This is a sub-menu for the master editor menu, so it should bring you there instead of the main menu

2024-11-13 02:03 UTC, liamp0924 commented on assets/shared/sounds/breakfast.ogg
i updated the pull request.

2024-11-13 20:43 UTC, liamp0924 commented on source/states/editors/ResultPreviewMenu.hx
> +			MusicBeatState.switchState(new MainMenuState());
@mikolka9144 i updated the pull request

2024-11-13 21:29 UTC, merged